Add support for host field
alessandroaime/homebridge-ueboom pull request #1
Opened 2019-12-10 14:48 UTC by newtonlb

This host field is necessary since the value of the gatttool command depends of which device UE BOOM was configured. In that case, is the MAC address of the device (in my case, my iPhone) + 01

I changed the readme as well.

2019-12-11 08:03 UTC, alessandroaime requested changes
Thanks for the heads up.

A couple of things: first, please re-submit the PR for the `development` branch as I will then personally merge it to `master` only once I make a new npm release and the `README` is properly phrased.

Other changes I would do before merging are:

* rename `mac` to `speaker` since now we're dealing with two MAC addresses and that might be confusing (the change has to be propagated also in `index.js`)
* have the host as the MAC address of the target device (iPhone in our case) and then append `01` in `command`:

```bash
const command = "gatttool -i hci0 -b " + this.speaker + " --char-write-req -a 0x0003 -n " + this.host + "01";
```

* the description of host is unclear, please change the `Find out the MAC address` and your `Host` section into:

```markdown
## Required parameters

To get the plugin working you have to provide the following parameters:

  * `speaker`: MAC address of the speaker
  * `host`: MAC address of the music source device (iPhone, ...)

In case you don't know how to retrieve the MAC address of the speaker:

  1. Pair the speaker to your MacBook
  2. Click on Bluetooth icon in the Menu Bar while pressing `⌥ Option`
  3. Select the speaker of which you need the address
  4. Write down the MAC address

To retrieve the MAC address of the host, it strictly depends on the device you're using. If you're playing music from an iPhone/iPad then you can find it in `Settings > General > About > Bluetooth`.
```

2019-12-11 08:33 UTC, alessandroaime reviewed
I actually merged and made the changes myself. I'll add your name as a contributor in the README.

https://github.com/alessandroaime/homebridge-ueboom/tree/newtonlb-master

I like to keep the commit history as clean as possible, that's why I usually squash minor commits together and I never merge straight into `master`.

Thanks again for the valuable contribution!

2019-12-11 11:30 UTC, merged

2019-12-11 20:15 UTC, ScottEgan commented
Thanks for this finding this @newtonlb and thanks for merging at publishing a new npm release @alessandroaime! It's working well for me now.

2019-12-12 11:21 UTC, newtonlb commented
thank you @alessandroaime for merging the PR. thank you for accepting my contribution!